In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [6]:
import pickle

In [7]:
## Load the dataset
df = pd.read_csv("data_source/Churn_Modelling.csv")

In [8]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
## Preprocess the data
## Drop the Irrelevant features
df = df.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
## Encode Categorical variables
label_encoder  = LabelEncoder()
df["Gender"] = label_encoder.fit_transform(df["Gender"])

In [12]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [15]:
## One hot encode "Geography"
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder(sparse_output=False)
geo_encoder = onehot_encoder_geo.fit_transform(df[["Geography"]])

In [16]:
onehot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [19]:
geo_encoded_df = pd.DataFrame(geo_encoder, columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))

In [20]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [21]:
# Combine the one hot encoder columns with the original data
df = pd.concat([df.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [22]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [23]:
## Save the encoders, and the scaler
with open("label_encoder.pkl", "wb") as file:
    pickle.dump(label_encoder, file)
with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(onehot_encoder_geo, file)

In [26]:
## Divide the dataset into independent and dependent features
X = df.drop("Exited", axis= 1)
y = df["Exited"]

## Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
## Scale these features
scaler = StandardScaler()
x_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
9254,686,1,32,6,0.00,2,1,1,179093.26,1.0,0.0,0.0
1561,632,1,42,4,119624.60,2,1,1,195978.86,0.0,1.0,0.0
1670,559,1,24,3,114739.92,1,1,0,85891.02,0.0,0.0,1.0
6087,561,0,27,9,135637.00,1,1,0,153080.40,1.0,0.0,0.0
6669,517,1,56,9,142147.32,1,0,0,39488.04,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5734,768,1,54,8,69712.74,1,1,1,69381.05,1.0,0.0,0.0
5191,682,0,58,1,0.00,1,1,1,706.50,1.0,0.0,0.0
5390,735,0,38,1,0.00,3,0,0,92220.12,1.0,0.0,0.0
860,667,1,43,8,190227.46,1,1,0,97508.04,1.0,0.0,0.0
7270,697,1,51,1,147910.30,1,1,1,53581.14,0.0,1.0,0.0

In [28]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

### ANN Implemantation

In [29]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [32]:
## Build Our ANN Model
model = Sequential([
    Dense(64, activation="relu", input_shape = (X_train.shape[1], )), # HL1 Connected with input layer
    Dense(32, activation="relu",), ## HL2
    Dense(1, activation="sigmoid") # output layer

])

In [31]:
X_train.shape[1]

12

In [35]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.BinaryCrossentropy()

In [36]:
## compile the model
model.compile(optimizer=opt, loss=loss, metrics=["accuracy"])

In [38]:
## Setup the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [41]:
## Set up Early Stopping 
early_stopping_callback= EarlyStopping(monitor="val_loss", patience=15, restore_best_weights = True)

In [42]:
history = model.fit(
    X_train, y_train, validation_data=(X_test,y_test), epochs=100, callbacks=[tensflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 54.8049 - accuracy: 0.6754 - val_loss: 0.6848 - val_accuracy: 0.5710
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 4.7021 - accuracy: 0.6819 - val_loss: 0.7064 - val_accuracy: 0.4460
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 1.2610 - accuracy: 0.6984 - val_loss: 0.6717 - val_accuracy: 0.6440
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.9355 - accuracy: 0.7218 - val_loss: 0.6257 - val_accuracy: 0.7845
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7869 - accuracy: 0.7322 - val_loss: 0.5876 - val_accuracy: 0.8090
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.6898 - accuracy: 0.7471 - val_loss: 0.5389 - val_accuracy: 0.8045
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5682 - accuracy: 0.7704 - val_loss: 0.4883 - val_accuracy: 0.8035
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5746 - accuracy: 0.7666 - val_loss: 0.4933 - val_accuracy: 0.8035
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5531 - accuracy: 0.7865 - val_loss: 0.4969 - val_accuracy: 0.8035
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7919 - val_loss: 0.4853 - val_accuracy: 0.8035
Epoch 11/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5084 - accuracy: 0.7945 - val_loss: 0.4853 - val_accuracy: 0.8035
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7945 - val_loss: 0.4853 - val_accuracy: 0.8035
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4849 - val_accuracy: 0.8035
Epoch 14/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5093 - accuracy: 0.7937 - val_loss: 0.4845 - val_accuracy: 0.8035
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5105 - accuracy: 0.7945 - val_loss: 0.4845 - val_accuracy: 0.8035
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5078 - accuracy: 0.7945 - val_loss: 0.4845 - val_accuracy: 0.8035
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7945 - val_loss: 0.4846 - val_accuracy: 0.8035
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5077 - accuracy: 0.7945 - val_loss: 0.4843 - val_accuracy: 0.8035
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5080 - accuracy: 0.7945 - val_loss: 0.4841 - val_accuracy: 0.8035
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5074 - accuracy: 0.7945 - val_loss: 0.4842 - val_accuracy: 0.8035
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5074 - accuracy: 0.7945 - val_loss: 0.4834 - val_accuracy: 0.8035
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7945 - val_loss: 0.4839 - val_accuracy: 0.8035
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5091 - accuracy: 0.7945 - val_loss: 0.4849 - val_accuracy: 0.8035
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4838 - val_accuracy: 0.8035
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7945 - val_loss: 0.4841 - val_accuracy: 0.8035
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5077 - accuracy: 0.7945 - val_loss: 0.4839 - val_accuracy: 0.8035
Epoch 27/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5078 - accuracy: 0.7945 - val_loss: 0.4839 - val_accuracy: 0.8035
Epoch 28/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5083 - accuracy: 0.7945 - val_loss: 0.4833 - val_accuracy: 0.8035
Epoch 29/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5080 - accuracy: 0.7945 - val_loss: 0.4830 - val_accuracy: 0.8035
Epoch 30/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7945 - val_loss: 0.4836 - val_accuracy: 0.8035
Epoch 31/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5076 - accuracy: 0.7945 - val_loss: 0.4835 - val_accuracy: 0.8035
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.4832 - val_accuracy: 0.8035
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5092 - accuracy: 0.7945 - val_loss: 0.4829 - val_accuracy: 0.8035
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5083 - accuracy: 0.7945 - val_loss: 0.4838 - val_accuracy: 0.8035
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4843 - val_accuracy: 0.8035
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.4839 - val_accuracy: 0.8035
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4868 - val_accuracy: 0.8035
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5084 - accuracy: 0.7945 - val_loss: 0.4838 - val_accuracy: 0.8035
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.4842 - val_accuracy: 0.8035
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5077 - accuracy: 0.7945 - val_loss: 0.4851 - val_accuracy: 0.8035
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7944 - val_loss: 0.4866 - val_accuracy: 0.8035
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.4846 - val_accuracy: 0.8035
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5080 - accuracy: 0.7945 - val_loss: 0.4856 - val_accuracy: 0.8035
Epoch 44/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4860 - val_accuracy: 0.8035
Epoch 45/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7985 - accuracy: 0.7934 - val_loss: 0.4859 - val_accuracy: 0.8055
Epoch 46/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5149 - accuracy: 0.7936 - val_loss: 0.4830 - val_accuracy: 0.8035
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7943 - val_loss: 0.4816 - val_accuracy: 0.8035
Epoch 48/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5085 - accuracy: 0.7944 - val_loss: 0.4814 - val_accuracy: 0.8035
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7945 - val_loss: 0.4814 - val_accuracy: 0.8035
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4813 - val_accuracy: 0.8035
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5083 - accuracy: 0.7945 - val_loss: 0.4811 - val_accuracy: 0.8035
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5076 - accuracy: 0.7945 - val_loss: 0.4813 - val_accuracy: 0.8035
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4807 - val_accuracy: 0.8035
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4807 - val_accuracy: 0.8035
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4807 - val_accuracy: 0.8035
Epoch 56/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4810 - val_accuracy: 0.8035
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5083 - accuracy: 0.7945 - val_loss: 0.4812 - val_accuracy: 0.8035
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4809 - val_accuracy: 0.8035
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5084 - accuracy: 0.7945 - val_loss: 0.4811 - val_accuracy: 0.8035
Epoch 60/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4820 - val_accuracy: 0.8035
Epoch 61/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5095 - accuracy: 0.7940 - val_loss: 0.4891 - val_accuracy: 0.8035
Epoch 62/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7945 - val_loss: 0.4906 - val_accuracy: 0.8035
Epoch 63/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7945 - val_loss: 0.4900 - val_accuracy: 0.8035
Epoch 64/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4905 - val_accuracy: 0.8035
Epoch 65/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4915 - val_accuracy: 0.8035
Epoch 66/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7945 - val_loss: 0.4893 - val_accuracy: 0.8035
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.4890 - val_accuracy: 0.8035
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5081 - accuracy: 0.7945 - val_loss: 0.4888 - val_accuracy: 0.8035
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.4887 - val_accuracy: 0.8035
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.4889 - val_accuracy: 0.8035

In [43]:
model.save("model.h5")

c:\Users\n\ANN Classification Project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [45]:
## load tensorboard extension
%load_ext tensorboard

In [48]:
%tensorboard --logdir logs/fit20260303-183508/

Reusing TensorBoard on port 6007 (pid 7556), started 0:01:11 ago. (Use '!kill 7556' to kill it.)

In [ ]:
## Load the pickle file